// Auto-generated by scripts/generate-mono-signatures.ts; do not edit by hand.
// Additional signatures can be added in src/runtime/signatures/manual.ts

import type { MonoExportSignature } from "./types.js";

export const GENERATED_SIGNATURES: Record<string, MonoExportSignature> = {
  mono_add_internal_call: {
    name: "mono_add_internal_call",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_aot_register_module: {
    name: "mono_aot_register_module",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_array_addr_with_size: {
    name: "mono_array_addr_with_size",
    retType: "pointer",
    argTypes: ["pointer", "int", "size_t"],
  },
  mono_array_class_get: {
    name: "mono_array_class_get",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_array_clone: {
    name: "mono_array_clone",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_array_element_size: {
    name: "mono_array_element_size",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_array_length: {
    name: "mono_array_length",
    retType: "size_t",
    argTypes: ["pointer"],
  },
  mono_array_new: {
    name: "mono_array_new",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "size_t"],
  },
  mono_array_new_full: {
    name: "mono_array_new_full",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_array_new_specific: {
    name: "mono_array_new_specific",
    retType: "pointer",
    argTypes: ["pointer", "size_t"],
  },
  mono_assemblies_cleanup: {
    name: "mono_assemblies_cleanup",
    retType: "void",
    argTypes: [],
  },
  mono_assemblies_init: {
    name: "mono_assemblies_init",
    retType: "void",
    argTypes: [],
  },
  mono_assembly_close: {
    name: "mono_assembly_close",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_assembly_fill_assembly_name: {
    name: "mono_assembly_fill_assembly_name",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_assembly_foreach: {
    name: "mono_assembly_foreach",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_assembly_get_assemblyref: {
    name: "mono_assembly_get_assemblyref",
    retType: "void",
    argTypes: ["pointer", "int", "pointer"],
  },
  mono_assembly_get_image: {
    name: "mono_assembly_get_image",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_get_main: {
    name: "mono_assembly_get_main",
    retType: "pointer",
    argTypes: [],
  },
  mono_assembly_get_name: {
    name: "mono_assembly_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_get_object: {
    name: "mono_assembly_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_assembly_getrootdir: {
    name: "mono_assembly_getrootdir",
    retType: "pointer",
    argTypes: [],
  },
  mono_assembly_invoke_load_hook: {
    name: "mono_assembly_invoke_load_hook",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_assembly_invoke_search_hook: {
    name: "mono_assembly_invoke_search_hook",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_load: {
    name: "mono_assembly_load",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_assembly_load_from: {
    name: "mono_assembly_load_from",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_assembly_load_from_full: {
    name: "mono_assembly_load_from_full",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "int"],
  },
  mono_assembly_load_full: {
    name: "mono_assembly_load_full",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "int"],
  },
  mono_assembly_load_module: {
    name: "mono_assembly_load_module",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_assembly_load_reference: {
    name: "mono_assembly_load_reference",
    retType: "void",
    argTypes: ["pointer", "int"],
  },
  mono_assembly_load_references: {
    name: "mono_assembly_load_references",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_assembly_load_with_partial_name: {
    name: "mono_assembly_load_with_partial_name",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_assembly_loaded: {
    name: "mono_assembly_loaded",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_loaded_full: {
    name: "mono_assembly_loaded_full",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_assembly_name_free: {
    name: "mono_assembly_name_free",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_assembly_name_get_culture: {
    name: "mono_assembly_name_get_culture",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_name_get_name: {
    name: "mono_assembly_name_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_name_get_pubkeytoken: {
    name: "mono_assembly_name_get_pubkeytoken",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_name_get_version: {
    name: "mono_assembly_name_get_version",
    retType: "uint",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_assembly_name_new: {
    name: "mono_assembly_name_new",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_assembly_names_equal: {
    name: "mono_assembly_names_equal",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_assembly_open: {
    name: "mono_assembly_open",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_assembly_open_full: {
    name: "mono_assembly_open_full",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_assembly_set_main: {
    name: "mono_assembly_set_main",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_assembly_setrootdir: {
    name: "mono_assembly_setrootdir",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_bounded_array_class_get: {
    name: "mono_bounded_array_class_get",
    retType: "pointer",
    argTypes: ["pointer", "uint", "int"],
  },
  mono_class_array_element_size: {
    name: "mono_class_array_element_size",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_data_size: {
    name: "mono_class_data_size",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_enum_basetype: {
    name: "mono_class_enum_basetype",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_from_generic_parameter: {
    name: "mono_class_from_generic_parameter",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_class_from_mono_type: {
    name: "mono_class_from_mono_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_from_name: {
    name: "mono_class_from_name",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_class_from_name_case: {
    name: "mono_class_from_name_case",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_class_from_typeref: {
    name: "mono_class_from_typeref",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_class_from_typeref_checked: {
    name: "mono_class_from_typeref_checked",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_class_get: {
    name: "mono_class_get",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_class_get_byref_type: {
    name: "mono_class_get_byref_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_element_class: {
    name: "mono_class_get_element_class",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_event_token: {
    name: "mono_class_get_event_token",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_class_get_events: {
    name: "mono_class_get_events",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_field: {
    name: "mono_class_get_field",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_class_get_field_from_name: {
    name: "mono_class_get_field_from_name",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_field_token: {
    name: "mono_class_get_field_token",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_class_get_fields: {
    name: "mono_class_get_fields",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_flags: {
    name: "mono_class_get_flags",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_class_get_full: {
    name: "mono_class_get_full",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_class_get_image: {
    name: "mono_class_get_image",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_interfaces: {
    name: "mono_class_get_interfaces",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_method_from_name: {
    name: "mono_class_get_method_from_name",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_class_get_method_from_name_flags: {
    name: "mono_class_get_method_from_name_flags",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int", "int"],
  },
  mono_class_get_methods: {
    name: "mono_class_get_methods",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_name: {
    name: "mono_class_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_namespace: {
    name: "mono_class_get_namespace",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_nested_types: {
    name: "mono_class_get_nested_types",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_nesting_type: {
    name: "mono_class_get_nesting_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_nullable_param: {
    name: "mono_class_get_nullable_param",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_parent: {
    name: "mono_class_get_parent",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_properties: {
    name: "mono_class_get_properties",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_property_from_name: {
    name: "mono_class_get_property_from_name",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_get_property_token: {
    name: "mono_class_get_property_token",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_class_get_rank: {
    name: "mono_class_get_rank",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_get_type: {
    name: "mono_class_get_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_class_get_type_token: {
    name: "mono_class_get_type_token",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_class_implements_interface: {
    name: "mono_class_implements_interface",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_inflate_generic_method: {
    name: "mono_class_inflate_generic_method",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_inflate_generic_type: {
    name: "mono_class_inflate_generic_type",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_init: {
    name: "mono_class_init",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_instance_size: {
    name: "mono_class_instance_size",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_is_assignable_from: {
    name: "mono_class_is_assignable_from",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_is_delegate: {
    name: "mono_class_is_delegate",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_is_enum: {
    name: "mono_class_is_enum",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_is_nullable: {
    name: "mono_class_is_nullable",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_is_subclass_of: {
    name: "mono_class_is_subclass_of",
    retType: "int",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_class_is_valuetype: {
    name: "mono_class_is_valuetype",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_min_align: {
    name: "mono_class_min_align",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_name_from_token: {
    name: "mono_class_name_from_token",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_class_num_events: {
    name: "mono_class_num_events",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_num_fields: {
    name: "mono_class_num_fields",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_num_methods: {
    name: "mono_class_num_methods",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_num_properties: {
    name: "mono_class_num_properties",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_class_value_size: {
    name: "mono_class_value_size",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_class_vtable: {
    name: "mono_class_vtable",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_compile_method: {
    name: "mono_compile_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_context_get_desc: {
    name: "mono_context_get_desc",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_custom_attrs_construct: {
    name: "mono_custom_attrs_construct",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_custom_attrs_free: {
    name: "mono_custom_attrs_free",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_custom_attrs_from_assembly: {
    name: "mono_custom_attrs_from_assembly",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_custom_attrs_from_class: {
    name: "mono_custom_attrs_from_class",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_custom_attrs_from_event: {
    name: "mono_custom_attrs_from_event",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_custom_attrs_from_field: {
    name: "mono_custom_attrs_from_field",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_custom_attrs_from_index: {
    name: "mono_custom_attrs_from_index",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_custom_attrs_from_method: {
    name: "mono_custom_attrs_from_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_custom_attrs_from_param: {
    name: "mono_custom_attrs_from_param",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_custom_attrs_from_property: {
    name: "mono_custom_attrs_from_property",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_custom_attrs_get_attr: {
    name: "mono_custom_attrs_get_attr",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_custom_attrs_has_attr: {
    name: "mono_custom_attrs_has_attr",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_dangerous_add_raw_internal_call: {
    name: "mono_dangerous_add_raw_internal_call",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_debug_add_delegate_trampoline: {
    name: "mono_debug_add_delegate_trampoline",
    retType: "void",
    argTypes: ["pointer", "int"],
  },
  mono_debug_add_method: {
    name: "mono_debug_add_method",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_debug_cleanup: {
    name: "mono_debug_cleanup",
    retType: "void",
    argTypes: [],
  },
  mono_debug_close_image: {
    name: "mono_debug_close_image",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_debug_domain_create: {
    name: "mono_debug_domain_create",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_debug_domain_unload: {
    name: "mono_debug_domain_unload",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_debug_enabled: {
    name: "mono_debug_enabled",
    retType: "int",
    argTypes: [],
  },
  mono_debug_find_method: {
    name: "mono_debug_find_method",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_debug_free_method_jit_info: {
    name: "mono_debug_free_method_jit_info",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_debug_free_source_location: {
    name: "mono_debug_free_source_location",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_debug_get_handle: {
    name: "mono_debug_get_handle",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_debug_il_offset_from_address: {
    name: "mono_debug_il_offset_from_address",
    retType: "int",
    argTypes: ["pointer", "pointer", "uint"],
  },
  mono_debug_init: {
    name: "mono_debug_init",
    retType: "void",
    argTypes: ["int"],
  },
  mono_debug_lookup_locals: {
    name: "mono_debug_lookup_locals",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_debug_lookup_method: {
    name: "mono_debug_lookup_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_debug_lookup_method_addresses: {
    name: "mono_debug_lookup_method_addresses",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_debug_lookup_source_location: {
    name: "mono_debug_lookup_source_location",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_debug_method_lookup_location: {
    name: "mono_debug_method_lookup_location",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_debug_open_image_from_memory: {
    name: "mono_debug_open_image_from_memory",
    retType: "void",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_debug_print_stack_frame: {
    name: "mono_debug_print_stack_frame",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_debug_remove_method: {
    name: "mono_debug_remove_method",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_debugger_insert_breakpoint: {
    name: "mono_debugger_insert_breakpoint",
    retType: "int",
    argTypes: ["pointer", "int"],
  },
  mono_debugger_method_has_breakpoint: {
    name: "mono_debugger_method_has_breakpoint",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_declsec_flags_from_assembly: {
    name: "mono_declsec_flags_from_assembly",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_declsec_flags_from_class: {
    name: "mono_declsec_flags_from_class",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_declsec_flags_from_method: {
    name: "mono_declsec_flags_from_method",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_declsec_get_assembly_action: {
    name: "mono_declsec_get_assembly_action",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_declsec_get_class_action: {
    name: "mono_declsec_get_class_action",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_declsec_get_demands: {
    name: "mono_declsec_get_demands",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_declsec_get_inheritdemands_class: {
    name: "mono_declsec_get_inheritdemands_class",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_declsec_get_inheritdemands_method: {
    name: "mono_declsec_get_inheritdemands_method",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_declsec_get_linkdemands: {
    name: "mono_declsec_get_linkdemands",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_declsec_get_method_action: {
    name: "mono_declsec_get_method_action",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_disasm_code: {
    name: "mono_disasm_code",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_disasm_code_one: {
    name: "mono_disasm_code_one",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_dllmap_insert: {
    name: "mono_dllmap_insert",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer", "pointer", "pointer"],
  },
  mono_environment_exitcode_get: {
    name: "mono_environment_exitcode_get",
    retType: "int",
    argTypes: [],
  },
  mono_environment_exitcode_set: {
    name: "mono_environment_exitcode_set",
    retType: "void",
    argTypes: ["int"],
  },
  mono_event_get_add_method: {
    name: "mono_event_get_add_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_event_get_flags: {
    name: "mono_event_get_flags",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_event_get_name: {
    name: "mono_event_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_event_get_object: {
    name: "mono_event_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_event_get_parent: {
    name: "mono_event_get_parent",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_event_get_raise_method: {
    name: "mono_event_get_raise_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_event_get_remove_method: {
    name: "mono_event_get_remove_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_field_from_token: {
    name: "mono_field_from_token",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer", "pointer"],
  },
  mono_field_full_name: {
    name: "mono_field_full_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_field_get_data: {
    name: "mono_field_get_data",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_field_get_flags: {
    name: "mono_field_get_flags",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_field_get_name: {
    name: "mono_field_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_field_get_object: {
    name: "mono_field_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_field_get_offset: {
    name: "mono_field_get_offset",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_field_get_parent: {
    name: "mono_field_get_parent",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_field_get_type: {
    name: "mono_field_get_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_field_get_value: {
    name: "mono_field_get_value",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_field_get_value_object: {
    name: "mono_field_get_value_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_field_set_value: {
    name: "mono_field_set_value",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_field_static_get_value: {
    name: "mono_field_static_get_value",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_field_static_set_value: {
    name: "mono_field_static_set_value",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_free: {
    name: "mono_free",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_free_method: {
    name: "mono_free_method",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_gc_collect: {
    name: "mono_gc_collect",
    retType: "void",
    argTypes: ["int"],
  },
  mono_gc_collection_count: {
    name: "mono_gc_collection_count",
    retType: "int",
    argTypes: ["int"],
  },
  mono_gc_finalize_notify: {
    name: "mono_gc_finalize_notify",
    retType: "void",
    argTypes: [],
  },
  mono_gc_get_generation: {
    name: "mono_gc_get_generation",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_gc_get_heap_size: {
    name: "mono_gc_get_heap_size",
    retType: "int64",
    argTypes: [],
  },
  mono_gc_get_used_size: {
    name: "mono_gc_get_used_size",
    retType: "int64",
    argTypes: [],
  },
  mono_gc_init_finalizer_thread: {
    name: "mono_gc_init_finalizer_thread",
    retType: "void",
    argTypes: [],
  },
  mono_gc_invoke_finalizers: {
    name: "mono_gc_invoke_finalizers",
    retType: "int",
    argTypes: [],
  },
  mono_gc_max_generation: {
    name: "mono_gc_max_generation",
    retType: "int",
    argTypes: [],
  },
  mono_gc_pending_finalizers: {
    name: "mono_gc_pending_finalizers",
    retType: "pointer",
    argTypes: [],
  },
  mono_gc_reference_queue_add: {
    name: "mono_gc_reference_queue_add",
    retType: "int",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_gc_reference_queue_free: {
    name: "mono_gc_reference_queue_free",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_gc_reference_queue_new: {
    name: "mono_gc_reference_queue_new",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_gc_walk_heap: {
    name: "mono_gc_walk_heap",
    retType: "int",
    argTypes: ["int", "pointer", "pointer"],
  },
  mono_gc_wbarrier_arrayref_copy: {
    name: "mono_gc_wbarrier_arrayref_copy",
    retType: "void",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_gc_wbarrier_generic_nostore: {
    name: "mono_gc_wbarrier_generic_nostore",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_gc_wbarrier_generic_store: {
    name: "mono_gc_wbarrier_generic_store",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_gc_wbarrier_generic_store_atomic: {
    name: "mono_gc_wbarrier_generic_store_atomic",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_gc_wbarrier_object_copy: {
    name: "mono_gc_wbarrier_object_copy",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_gc_wbarrier_set_arrayref: {
    name: "mono_gc_wbarrier_set_arrayref",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_gc_wbarrier_set_field: {
    name: "mono_gc_wbarrier_set_field",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_gc_wbarrier_value_copy: {
    name: "mono_gc_wbarrier_value_copy",
    retType: "void",
    argTypes: ["pointer", "pointer", "int", "pointer"],
  },
  mono_gchandle_free: {
    name: "mono_gchandle_free",
    retType: "void",
    argTypes: ["uint"],
  },
  mono_gchandle_free_v2: {
    name: "mono_gchandle_free_v2",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_gchandle_get_target: {
    name: "mono_gchandle_get_target",
    retType: "pointer",
    argTypes: ["uint"],
  },
  mono_gchandle_get_target_v2: {
    name: "mono_gchandle_get_target_v2",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_gchandle_new: {
    name: "mono_gchandle_new",
    retType: "uint",
    argTypes: ["pointer", "int"],
  },
  mono_gchandle_new_v2: {
    name: "mono_gchandle_new_v2",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_gchandle_new_weakref: {
    name: "mono_gchandle_new_weakref",
    retType: "uint",
    argTypes: ["pointer", "int"],
  },
  mono_gchandle_new_weakref_v2: {
    name: "mono_gchandle_new_weakref_v2",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_get_dbnull_object: {
    name: "mono_get_dbnull_object",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_get_delegate_begin_invoke: {
    name: "mono_get_delegate_begin_invoke",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_get_delegate_end_invoke: {
    name: "mono_get_delegate_end_invoke",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_get_delegate_invoke: {
    name: "mono_get_delegate_invoke",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_get_inflated_method: {
    name: "mono_get_inflated_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_get_method: {
    name: "mono_get_method",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_get_method_constrained: {
    name: "mono_get_method_constrained",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer", "pointer", "pointer"],
  },
  mono_get_method_full: {
    name: "mono_get_method_full",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer", "pointer"],
  },
  mono_get_runtime_build_info: {
    name: "mono_get_runtime_build_info",
    retType: "pointer",
    argTypes: [],
  },
  mono_guid_to_string: {
    name: "mono_guid_to_string",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_guid_to_string_minimal: {
    name: "mono_guid_to_string_minimal",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_image_add_to_name_cache: {
    name: "mono_image_add_to_name_cache",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer", "uint"],
  },
  mono_image_addref: {
    name: "mono_image_addref",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_image_close: {
    name: "mono_image_close",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_image_ensure_section: {
    name: "mono_image_ensure_section",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_image_ensure_section_idx: {
    name: "mono_image_ensure_section_idx",
    retType: "int",
    argTypes: ["pointer", "int"],
  },
  mono_image_fixup_vtable: {
    name: "mono_image_fixup_vtable",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_image_get_assembly: {
    name: "mono_image_get_assembly",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_image_get_entry_point: {
    name: "mono_image_get_entry_point",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_image_get_filename: {
    name: "mono_image_get_filename",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_image_get_guid: {
    name: "mono_image_get_guid",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_image_get_name: {
    name: "mono_image_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_image_get_public_key: {
    name: "mono_image_get_public_key",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_image_get_resource: {
    name: "mono_image_get_resource",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_image_get_strong_name: {
    name: "mono_image_get_strong_name",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_image_get_table_info: {
    name: "mono_image_get_table_info",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_image_get_table_rows: {
    name: "mono_image_get_table_rows",
    retType: "int",
    argTypes: ["pointer", "int"],
  },
  mono_image_has_authenticode_entry: {
    name: "mono_image_has_authenticode_entry",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_image_init: {
    name: "mono_image_init",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_image_is_dynamic: {
    name: "mono_image_is_dynamic",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_image_load_file_for_image: {
    name: "mono_image_load_file_for_image",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_image_load_module: {
    name: "mono_image_load_module",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_image_loaded: {
    name: "mono_image_loaded",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_image_loaded_by_guid: {
    name: "mono_image_loaded_by_guid",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_image_loaded_by_guid_full: {
    name: "mono_image_loaded_by_guid_full",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_image_loaded_full: {
    name: "mono_image_loaded_full",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_image_lookup_resource: {
    name: "mono_image_lookup_resource",
    retType: "pointer",
    argTypes: ["pointer", "uint", "uint", "pointer"],
  },
  mono_image_open: {
    name: "mono_image_open",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_image_open_from_data: {
    name: "mono_image_open_from_data",
    retType: "pointer",
    argTypes: ["pointer", "uint", "int", "pointer"],
  },
  mono_image_open_from_data_full: {
    name: "mono_image_open_from_data_full",
    retType: "pointer",
    argTypes: ["pointer", "uint", "int", "pointer", "int"],
  },
  mono_image_open_from_data_with_name: {
    name: "mono_image_open_from_data_with_name",
    retType: "pointer",
    argTypes: ["pointer", "uint", "int", "pointer", "int", "pointer"],
  },
  mono_image_open_full: {
    name: "mono_image_open_full",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_image_rva_map: {
    name: "mono_image_rva_map",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_image_strerror: {
    name: "mono_image_strerror",
    retType: "pointer",
    argTypes: ["int"],
  },
  mono_image_strong_name_position: {
    name: "mono_image_strong_name_position",
    retType: "uint",
    argTypes: ["pointer", "pointer"],
  },
  mono_images_cleanup: {
    name: "mono_images_cleanup",
    retType: "void",
    argTypes: [],
  },
  mono_images_init: {
    name: "mono_images_init",
    retType: "void",
    argTypes: [],
  },
  mono_install_assembly_load_hook: {
    name: "mono_install_assembly_load_hook",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_install_assembly_postload_refonly_search_hook: {
    name: "mono_install_assembly_postload_refonly_search_hook",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_install_assembly_postload_search_hook: {
    name: "mono_install_assembly_postload_search_hook",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_install_assembly_preload_hook: {
    name: "mono_install_assembly_preload_hook",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_install_assembly_refonly_preload_hook: {
    name: "mono_install_assembly_refonly_preload_hook",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_install_assembly_refonly_search_hook: {
    name: "mono_install_assembly_refonly_search_hook",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_install_assembly_search_hook: {
    name: "mono_install_assembly_search_hook",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_is_debugger_attached: {
    name: "mono_is_debugger_attached",
    retType: "int",
    argTypes: [],
  },
  mono_jit_aot_compiling: {
    name: "mono_jit_aot_compiling",
    retType: "int",
    argTypes: [],
  },
  mono_jit_cleanup: {
    name: "mono_jit_cleanup",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_jit_exec: {
    name: "mono_jit_exec",
    retType: "int",
    argTypes: ["pointer", "pointer", "int", "pointer"],
  },
  mono_jit_init: {
    name: "mono_jit_init",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_jit_init_version: {
    name: "mono_jit_init_version",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_jit_init_version_for_test_only: {
    name: "mono_jit_init_version_for_test_only",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_jit_parse_options: {
    name: "mono_jit_parse_options",
    retType: "void",
    argTypes: ["int", "pointer"],
  },
  mono_jit_set_aot_mode: {
    name: "mono_jit_set_aot_mode",
    retType: "void",
    argTypes: ["int"],
  },
  mono_jit_set_aot_only: {
    name: "mono_jit_set_aot_only",
    retType: "void",
    argTypes: ["int"],
  },
  mono_jit_set_trace_options: {
    name: "mono_jit_set_trace_options",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_jit_thread_attach: {
    name: "mono_jit_thread_attach",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_ldstr: {
    name: "mono_ldstr",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "uint"],
  },
  mono_ldtoken: {
    name: "mono_ldtoken",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer", "pointer"],
  },
  mono_load_remote_field: {
    name: "mono_load_remote_field",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_load_remote_field_new: {
    name: "mono_load_remote_field_new",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_lookup_icall_symbol: {
    name: "mono_lookup_icall_symbol",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_lookup_internal_call: {
    name: "mono_lookup_internal_call",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_lookup_pinvoke_call: {
    name: "mono_lookup_pinvoke_call",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_metadata_blob_heap: {
    name: "mono_metadata_blob_heap",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_compute_size: {
    name: "mono_metadata_compute_size",
    retType: "int",
    argTypes: ["pointer", "int", "pointer"],
  },
  mono_metadata_custom_attrs_from_index: {
    name: "mono_metadata_custom_attrs_from_index",
    retType: "uint",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_declsec_from_index: {
    name: "mono_metadata_declsec_from_index",
    retType: "uint",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_decode_blob_size: {
    name: "mono_metadata_decode_blob_size",
    retType: "uint",
    argTypes: ["pointer", "pointer"],
  },
  mono_metadata_decode_row: {
    name: "mono_metadata_decode_row",
    retType: "void",
    argTypes: ["pointer", "int", "pointer", "int"],
  },
  mono_metadata_decode_row_col: {
    name: "mono_metadata_decode_row_col",
    retType: "uint",
    argTypes: ["pointer", "int", "uint"],
  },
  mono_metadata_decode_signed_value: {
    name: "mono_metadata_decode_signed_value",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_metadata_decode_table_row: {
    name: "mono_metadata_decode_table_row",
    retType: "void",
    argTypes: ["pointer", "int", "int", "pointer", "int"],
  },
  mono_metadata_decode_table_row_col: {
    name: "mono_metadata_decode_table_row_col",
    retType: "uint",
    argTypes: ["pointer", "int", "int", "uint"],
  },
  mono_metadata_decode_value: {
    name: "mono_metadata_decode_value",
    retType: "uint",
    argTypes: ["pointer", "pointer"],
  },
  mono_metadata_encode_value: {
    name: "mono_metadata_encode_value",
    retType: "void",
    argTypes: ["uint", "pointer", "pointer"],
  },
  mono_metadata_events_from_typedef: {
    name: "mono_metadata_events_from_typedef",
    retType: "uint",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_metadata_field_info: {
    name: "mono_metadata_field_info",
    retType: "void",
    argTypes: ["pointer", "uint", "pointer", "pointer", "pointer"],
  },
  mono_metadata_free_array: {
    name: "mono_metadata_free_array",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_metadata_free_marshal_spec: {
    name: "mono_metadata_free_marshal_spec",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_metadata_free_method_signature: {
    name: "mono_metadata_free_method_signature",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_metadata_free_mh: {
    name: "mono_metadata_free_mh",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_metadata_free_type: {
    name: "mono_metadata_free_type",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_metadata_generic_class_is_valuetype: {
    name: "mono_metadata_generic_class_is_valuetype",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_metadata_get_constant_index: {
    name: "mono_metadata_get_constant_index",
    retType: "uint",
    argTypes: ["pointer", "uint", "uint"],
  },
  mono_metadata_get_marshal_info: {
    name: "mono_metadata_get_marshal_info",
    retType: "pointer",
    argTypes: ["pointer", "uint", "int"],
  },
  mono_metadata_guid_heap: {
    name: "mono_metadata_guid_heap",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_implmap_from_method: {
    name: "mono_metadata_implmap_from_method",
    retType: "uint",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_init: {
    name: "mono_metadata_init",
    retType: "void",
    argTypes: [],
  },
  mono_metadata_interfaces_from_typedef: {
    name: "mono_metadata_interfaces_from_typedef",
    retType: "pointer",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_metadata_locate: {
    name: "mono_metadata_locate",
    retType: "pointer",
    argTypes: ["pointer", "int", "int"],
  },
  mono_metadata_locate_token: {
    name: "mono_metadata_locate_token",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_methods_from_event: {
    name: "mono_metadata_methods_from_event",
    retType: "uint",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_metadata_methods_from_property: {
    name: "mono_metadata_methods_from_property",
    retType: "uint",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_metadata_nested_in_typedef: {
    name: "mono_metadata_nested_in_typedef",
    retType: "uint",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_nesting_typedef: {
    name: "mono_metadata_nesting_typedef",
    retType: "uint",
    argTypes: ["pointer", "uint", "uint"],
  },
  mono_metadata_packing_from_typedef: {
    name: "mono_metadata_packing_from_typedef",
    retType: "uint",
    argTypes: ["pointer", "uint", "pointer", "pointer"],
  },
  mono_metadata_parse_array: {
    name: "mono_metadata_parse_array",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_metadata_parse_custom_mod: {
    name: "mono_metadata_parse_custom_mod",
    retType: "int",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_metadata_parse_field_type: {
    name: "mono_metadata_parse_field_type",
    retType: "pointer",
    argTypes: ["pointer", "int", "pointer", "pointer"],
  },
  mono_metadata_parse_marshal_spec: {
    name: "mono_metadata_parse_marshal_spec",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_metadata_parse_method_signature: {
    name: "mono_metadata_parse_method_signature",
    retType: "pointer",
    argTypes: ["pointer", "int", "pointer", "pointer"],
  },
  mono_metadata_parse_mh: {
    name: "mono_metadata_parse_mh",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_metadata_parse_param: {
    name: "mono_metadata_parse_param",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_metadata_parse_signature: {
    name: "mono_metadata_parse_signature",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_parse_type: {
    name: "mono_metadata_parse_type",
    retType: "pointer",
    argTypes: ["pointer", "int", "int", "pointer", "pointer"],
  },
  mono_metadata_parse_typedef_or_ref: {
    name: "mono_metadata_parse_typedef_or_ref",
    retType: "uint",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_metadata_properties_from_typedef: {
    name: "mono_metadata_properties_from_typedef",
    retType: "uint",
    argTypes: ["pointer", "uint", "pointer"],
  },
  mono_metadata_signature_alloc: {
    name: "mono_metadata_signature_alloc",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_signature_dup: {
    name: "mono_metadata_signature_dup",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_metadata_signature_equal: {
    name: "mono_metadata_signature_equal",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_metadata_string_heap: {
    name: "mono_metadata_string_heap",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_token_from_dor: {
    name: "mono_metadata_token_from_dor",
    retType: "uint",
    argTypes: ["uint"],
  },
  mono_metadata_translate_token_index: {
    name: "mono_metadata_translate_token_index",
    retType: "uint",
    argTypes: ["pointer", "int", "uint"],
  },
  mono_metadata_type_equal: {
    name: "mono_metadata_type_equal",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_metadata_type_hash: {
    name: "mono_metadata_type_hash",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_metadata_typedef_from_field: {
    name: "mono_metadata_typedef_from_field",
    retType: "uint",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_typedef_from_method: {
    name: "mono_metadata_typedef_from_method",
    retType: "uint",
    argTypes: ["pointer", "uint"],
  },
  mono_metadata_user_string: {
    name: "mono_metadata_user_string",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_method_body_get_object: {
    name: "mono_method_body_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_can_access_field: {
    name: "mono_method_can_access_field",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_can_access_method: {
    name: "mono_method_can_access_method",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_desc_free: {
    name: "mono_method_desc_free",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_method_desc_from_method: {
    name: "mono_method_desc_from_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_method_desc_full_match: {
    name: "mono_method_desc_full_match",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_desc_is_full: {
    name: "mono_method_desc_is_full",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_method_desc_match: {
    name: "mono_method_desc_match",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_desc_new: {
    name: "mono_method_desc_new",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_method_desc_search_in_class: {
    name: "mono_method_desc_search_in_class",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_desc_search_in_image: {
    name: "mono_method_desc_search_in_image",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_full_name: {
    name: "mono_method_full_name",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_method_get_class: {
    name: "mono_method_get_class",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_method_get_flags: {
    name: "mono_method_get_flags",
    retType: "uint",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_get_header: {
    name: "mono_method_get_header",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_method_get_header_checked: {
    name: "mono_method_get_header_checked",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_get_index: {
    name: "mono_method_get_index",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_method_get_last_managed: {
    name: "mono_method_get_last_managed",
    retType: "pointer",
    argTypes: [],
  },
  mono_method_get_marshal_info: {
    name: "mono_method_get_marshal_info",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_get_name: {
    name: "mono_method_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_method_get_object: {
    name: "mono_method_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_method_get_param_names: {
    name: "mono_method_get_param_names",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_method_get_param_token: {
    name: "mono_method_get_param_token",
    retType: "uint",
    argTypes: ["pointer", "int"],
  },
  mono_method_get_reflection_name: {
    name: "mono_method_get_reflection_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_method_get_signature: {
    name: "mono_method_get_signature",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "uint"],
  },
  mono_method_get_signature_full: {
    name: "mono_method_get_signature_full",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "uint", "pointer"],
  },
  mono_method_get_token: {
    name: "mono_method_get_token",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_method_get_unmanaged_thunk: {
    name: "mono_method_get_unmanaged_thunk",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_method_has_marshal_info: {
    name: "mono_method_has_marshal_info",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_method_header_get_clauses: {
    name: "mono_method_header_get_clauses",
    retType: "int",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_method_header_get_code: {
    name: "mono_method_header_get_code",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_method_header_get_locals: {
    name: "mono_method_header_get_locals",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_method_header_get_num_clauses: {
    name: "mono_method_header_get_num_clauses",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_method_signature: {
    name: "mono_method_signature",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_module_file_get_object: {
    name: "mono_module_file_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_module_get_object: {
    name: "mono_module_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_monitor_enter: {
    name: "mono_monitor_enter",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_monitor_enter_v4: {
    name: "mono_monitor_enter_v4",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_monitor_exit: {
    name: "mono_monitor_exit",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_monitor_try_enter: {
    name: "mono_monitor_try_enter",
    retType: "int",
    argTypes: ["pointer", "uint"],
  },
  mono_native_getrootdir: {
    name: "mono_native_getrootdir",
    retType: "pointer",
    argTypes: [],
  },
  mono_object_castclass_mbyref: {
    name: "mono_object_castclass_mbyref",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_object_clone: {
    name: "mono_object_clone",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_object_get_class: {
    name: "mono_object_get_class",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_object_get_domain: {
    name: "mono_object_get_domain",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_object_get_size: {
    name: "mono_object_get_size",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_object_get_virtual_method: {
    name: "mono_object_get_virtual_method",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_object_get_vtable: {
    name: "mono_object_get_vtable",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_object_hash: {
    name: "mono_object_hash",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_object_isinst: {
    name: "mono_object_isinst",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_object_isinst_mbyref: {
    name: "mono_object_isinst_mbyref",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_object_new: {
    name: "mono_object_new",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_object_new_alloc_specific: {
    name: "mono_object_new_alloc_specific",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_object_new_fast: {
    name: "mono_object_new_fast",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_object_new_from_token: {
    name: "mono_object_new_from_token",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "uint"],
  },
  mono_object_new_specific: {
    name: "mono_object_new_specific",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_object_to_string: {
    name: "mono_object_to_string",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_object_unbox: {
    name: "mono_object_unbox",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_param_get_objects: {
    name: "mono_param_get_objects",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_path_canonicalize: {
    name: "mono_path_canonicalize",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_path_resolve_symlinks: {
    name: "mono_path_resolve_symlinks",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_pe_file_open: {
    name: "mono_pe_file_open",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_print_unhandled_exception: {
    name: "mono_print_unhandled_exception",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_profiler_call_context_free_buffer: {
    name: "mono_profiler_call_context_free_buffer",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_profiler_call_context_get_argument: {
    name: "mono_profiler_call_context_get_argument",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_profiler_call_context_get_local: {
    name: "mono_profiler_call_context_get_local",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_profiler_call_context_get_result: {
    name: "mono_profiler_call_context_get_result",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_profiler_call_context_get_this: {
    name: "mono_profiler_call_context_get_this",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_profiler_create: {
    name: "mono_profiler_create",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_profiler_enable_allocations: {
    name: "mono_profiler_enable_allocations",
    retType: "int",
    argTypes: [],
  },
  mono_profiler_enable_call_context_introspection: {
    name: "mono_profiler_enable_call_context_introspection",
    retType: "int",
    argTypes: [],
  },
  mono_profiler_enable_clauses: {
    name: "mono_profiler_enable_clauses",
    retType: "int",
    argTypes: [],
  },
  mono_profiler_enable_coverage: {
    name: "mono_profiler_enable_coverage",
    retType: "int",
    argTypes: [],
  },
  mono_profiler_enable_sampling: {
    name: "mono_profiler_enable_sampling",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_profiler_get_coverage_data: {
    name: "mono_profiler_get_coverage_data",
    retType: "int",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_profiler_get_sample_mode: {
    name: "mono_profiler_get_sample_mode",
    retType: "int",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_profiler_load: {
    name: "mono_profiler_load",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_profiler_set_call_instrumentation_filter_callback: {
    name: "mono_profiler_set_call_instrumentation_filter_callback",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_profiler_set_cleanup_callback: {
    name: "mono_profiler_set_cleanup_callback",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_profiler_set_coverage_filter_callback: {
    name: "mono_profiler_set_coverage_filter_callback",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_profiler_set_sample_mode: {
    name: "mono_profiler_set_sample_mode",
    retType: "int",
    argTypes: ["pointer", "int", "uint"],
  },
  mono_property_get_flags: {
    name: "mono_property_get_flags",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_property_get_get_method: {
    name: "mono_property_get_get_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_property_get_name: {
    name: "mono_property_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_property_get_object: {
    name: "mono_property_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_property_get_parent: {
    name: "mono_property_get_parent",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_property_get_set_method: {
    name: "mono_property_get_set_method",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_property_get_value: {
    name: "mono_property_get_value",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_property_set_value: {
    name: "mono_property_set_value",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_ptr_class_get: {
    name: "mono_ptr_class_get",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_raise_exception: {
    name: "mono_raise_exception",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_reflection_assembly_get_assembly: {
    name: "mono_reflection_assembly_get_assembly",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_reflection_free_type_info: {
    name: "mono_reflection_free_type_info",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_reflection_get_custom_attrs: {
    name: "mono_reflection_get_custom_attrs",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_reflection_get_custom_attrs_blob: {
    name: "mono_reflection_get_custom_attrs_blob",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer", "pointer", "pointer", "pointer"],
  },
  mono_reflection_get_custom_attrs_by_type: {
    name: "mono_reflection_get_custom_attrs_by_type",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_reflection_get_custom_attrs_data: {
    name: "mono_reflection_get_custom_attrs_data",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_reflection_get_custom_attrs_info: {
    name: "mono_reflection_get_custom_attrs_info",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_reflection_get_token: {
    name: "mono_reflection_get_token",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_reflection_get_type: {
    name: "mono_reflection_get_type",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int", "pointer"],
  },
  mono_reflection_parse_type: {
    name: "mono_reflection_parse_type",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_reflection_type_from_name: {
    name: "mono_reflection_type_from_name",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_reflection_type_get_type: {
    name: "mono_reflection_type_get_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_register_bundled_assemblies: {
    name: "mono_register_bundled_assemblies",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_register_config_for_assembly: {
    name: "mono_register_config_for_assembly",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_register_machine_config: {
    name: "mono_register_machine_config",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_register_symfile_for_assembly: {
    name: "mono_register_symfile_for_assembly",
    retType: "void",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_reraise_exception: {
    name: "mono_reraise_exception",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_runtime_class_init: {
    name: "mono_runtime_class_init",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_runtime_delegate_invoke: {
    name: "mono_runtime_delegate_invoke",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_runtime_exec_main: {
    name: "mono_runtime_exec_main",
    retType: "int",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_runtime_exec_managed_code: {
    name: "mono_runtime_exec_managed_code",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_runtime_get_main_args: {
    name: "mono_runtime_get_main_args",
    retType: "pointer",
    argTypes: [],
  },
  mono_runtime_invoke: {
    name: "mono_runtime_invoke",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_runtime_invoke_array: {
    name: "mono_runtime_invoke_array",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_runtime_object_init: {
    name: "mono_runtime_object_init",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_runtime_run_main: {
    name: "mono_runtime_run_main",
    retType: "int",
    argTypes: ["pointer", "int", "pointer", "pointer"],
  },
  mono_runtime_set_main_args: {
    name: "mono_runtime_set_main_args",
    retType: "int",
    argTypes: ["int", "pointer"],
  },
  mono_runtime_set_pending_exception: {
    name: "mono_runtime_set_pending_exception",
    retType: "int",
    argTypes: ["pointer", "int"],
  },
  mono_set_allocator_vtable: {
    name: "mono_set_allocator_vtable",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_set_assemblies_path: {
    name: "mono_set_assemblies_path",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_set_break_policy: {
    name: "mono_set_break_policy",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_set_crash_chaining: {
    name: "mono_set_crash_chaining",
    retType: "void",
    argTypes: ["int"],
  },
  mono_set_dirs: {
    name: "mono_set_dirs",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_set_is_debugger_attached: {
    name: "mono_set_is_debugger_attached",
    retType: "void",
    argTypes: ["int"],
  },
  mono_set_rootdir: {
    name: "mono_set_rootdir",
    retType: "void",
    argTypes: [],
  },
  mono_set_signal_chaining: {
    name: "mono_set_signal_chaining",
    retType: "void",
    argTypes: ["int"],
  },
  mono_set_use_llvm: {
    name: "mono_set_use_llvm",
    retType: "void",
    argTypes: ["int"],
  },
  mono_signature_explicit_this: {
    name: "mono_signature_explicit_this",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_signature_get_call_conv: {
    name: "mono_signature_get_call_conv",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_signature_get_desc: {
    name: "mono_signature_get_desc",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_signature_get_param_count: {
    name: "mono_signature_get_param_count",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_signature_get_params: {
    name: "mono_signature_get_params",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_signature_get_return_type: {
    name: "mono_signature_get_return_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_signature_hash: {
    name: "mono_signature_hash",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_signature_is_instance: {
    name: "mono_signature_is_instance",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_signature_param_is_out: {
    name: "mono_signature_param_is_out",
    retType: "int",
    argTypes: ["pointer", "int"],
  },
  mono_signature_vararg_start: {
    name: "mono_signature_vararg_start",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_stack_walk: {
    name: "mono_stack_walk",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_stack_walk_async_safe: {
    name: "mono_stack_walk_async_safe",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_stack_walk_no_il: {
    name: "mono_stack_walk_no_il",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_store_remote_field: {
    name: "mono_store_remote_field",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_store_remote_field_new: {
    name: "mono_store_remote_field_new",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer", "pointer"],
  },
  mono_string_chars: {
    name: "mono_string_chars",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_empty: {
    name: "mono_string_empty",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_empty_wrapper: {
    name: "mono_string_empty_wrapper",
    retType: "pointer",
    argTypes: [],
  },
  mono_string_equal: {
    name: "mono_string_equal",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_string_from_utf16: {
    name: "mono_string_from_utf16",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_from_utf32: {
    name: "mono_string_from_utf32",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_hash: {
    name: "mono_string_hash",
    retType: "uint",
    argTypes: ["pointer"],
  },
  mono_string_intern: {
    name: "mono_string_intern",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_is_interned: {
    name: "mono_string_is_interned",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_length: {
    name: "mono_string_length",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_string_new: {
    name: "mono_string_new",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_string_new_len: {
    name: "mono_string_new_len",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "uint"],
  },
  mono_string_new_size: {
    name: "mono_string_new_size",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_string_new_utf16: {
    name: "mono_string_new_utf16",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_string_new_utf32: {
    name: "mono_string_new_utf32",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "int"],
  },
  mono_string_new_wrapper: {
    name: "mono_string_new_wrapper",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_to_utf16: {
    name: "mono_string_to_utf16",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_to_utf32: {
    name: "mono_string_to_utf32",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_to_utf8: {
    name: "mono_string_to_utf8",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_string_to_utf8_checked: {
    name: "mono_string_to_utf8_checked",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_stringify_assembly_name: {
    name: "mono_stringify_assembly_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_table_info_get_rows: {
    name: "mono_table_info_get_rows",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_thread_attach: {
    name: "mono_thread_attach",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_thread_cleanup: {
    name: "mono_thread_cleanup",
    retType: "void",
    argTypes: [],
  },
  mono_thread_create: {
    name: "mono_thread_create",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_thread_current: {
    name: "mono_thread_current",
    retType: "pointer",
    argTypes: [],
  },
  mono_thread_detach: {
    name: "mono_thread_detach",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_thread_detach_if_exiting: {
    name: "mono_thread_detach_if_exiting",
    retType: "int",
    argTypes: [],
  },
  mono_thread_exit: {
    name: "mono_thread_exit",
    retType: "void",
    argTypes: [],
  },
  mono_thread_get_main: {
    name: "mono_thread_get_main",
    retType: "pointer",
    argTypes: [],
  },
  mono_thread_get_managed_id: {
    name: "mono_thread_get_managed_id",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_thread_get_name_utf8: {
    name: "mono_thread_get_name_utf8",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_thread_init: {
    name: "mono_thread_init",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_thread_is_foreign: {
    name: "mono_thread_is_foreign",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_thread_manage: {
    name: "mono_thread_manage",
    retType: "void",
    argTypes: [],
  },
  mono_thread_new_init: {
    name: "mono_thread_new_init",
    retType: "void",
    argTypes: ["long", "pointer", "pointer"],
  },
  mono_thread_set_main: {
    name: "mono_thread_set_main",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_thread_set_manage_callback: {
    name: "mono_thread_set_manage_callback",
    retType: "void",
    argTypes: ["pointer", "pointer"],
  },
  mono_thread_stop: {
    name: "mono_thread_stop",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_threads_attach_tools_thread: {
    name: "mono_threads_attach_tools_thread",
    retType: "void",
    argTypes: [],
  },
  mono_threads_get_default_stacksize: {
    name: "mono_threads_get_default_stacksize",
    retType: "uint",
    argTypes: [],
  },
  mono_threads_request_thread_dump: {
    name: "mono_threads_request_thread_dump",
    retType: "void",
    argTypes: [],
  },
  mono_threads_set_default_stacksize: {
    name: "mono_threads_set_default_stacksize",
    retType: "void",
    argTypes: ["uint"],
  },
  mono_type_create_from_typespec: {
    name: "mono_type_create_from_typespec",
    retType: "pointer",
    argTypes: ["pointer", "uint"],
  },
  mono_type_full_name: {
    name: "mono_type_full_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_type_generic_inst_is_valuetype: {
    name: "mono_type_generic_inst_is_valuetype",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_get_array_type: {
    name: "mono_type_get_array_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_type_get_class: {
    name: "mono_type_get_class",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_type_get_modifiers: {
    name: "mono_type_get_modifiers",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_type_get_name: {
    name: "mono_type_get_name",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_type_get_name_full: {
    name: "mono_type_get_name_full",
    retType: "pointer",
    argTypes: ["pointer", "int"],
  },
  mono_type_get_object: {
    name: "mono_type_get_object",
    retType: "pointer",
    argTypes: ["pointer", "pointer"],
  },
  mono_type_get_ptr_type: {
    name: "mono_type_get_ptr_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_type_get_signature: {
    name: "mono_type_get_signature",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_type_get_type: {
    name: "mono_type_get_type",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_get_underlying_type: {
    name: "mono_type_get_underlying_type",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_type_is_byref: {
    name: "mono_type_is_byref",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_is_generic_parameter: {
    name: "mono_type_is_generic_parameter",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_is_pointer: {
    name: "mono_type_is_pointer",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_is_reference: {
    name: "mono_type_is_reference",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_is_struct: {
    name: "mono_type_is_struct",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_is_void: {
    name: "mono_type_is_void",
    retType: "int",
    argTypes: ["pointer"],
  },
  mono_type_size: {
    name: "mono_type_size",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_type_stack_size: {
    name: "mono_type_stack_size",
    retType: "int",
    argTypes: ["pointer", "pointer"],
  },
  mono_type_to_unmanaged: {
    name: "mono_type_to_unmanaged",
    retType: "uint",
    argTypes: ["pointer", "pointer", "int", "int", "pointer"],
  },
  mono_unhandled_exception: {
    name: "mono_unhandled_exception",
    retType: "void",
    argTypes: ["pointer"],
  },
  mono_value_box: {
    name: "mono_value_box",
    retType: "pointer",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_value_copy: {
    name: "mono_value_copy",
    retType: "void",
    argTypes: ["pointer", "pointer", "pointer"],
  },
  mono_value_copy_array: {
    name: "mono_value_copy_array",
    retType: "void",
    argTypes: ["pointer", "int", "pointer", "int"],
  },
  mono_vtable_class: {
    name: "mono_vtable_class",
    retType: "pointer",
    argTypes: ["pointer"],
  },
  mono_vtable_domain: {
    name: "mono_vtable_domain",
    retType: "pointer",
    argTypes: ["pointer"],
  },
};
